### ISSUE TITLE
Translations in Spanish language of find issues page

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#11]
Translate lines of **Find issues and repositories** page in Spanish

Each line should be translated.
like -->
![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/110289710/7899b977-cd8f-4925-a26c-450db4addeb0)

Add the translations in the JSON format in a file called **es.json** inside a new folder **translations**
like -->
```
{
  "English line": "Spanish line",
  "....": ".....",
  ...
}
```

**Comment by AjinkyaBorate** [comment]
Made translations folder and added es.json in it
