### ISSUE TITLE
Add more topics in advanced git page

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#19]
Add topics to the Git advanced page in Advanced -> Git Advanced at the bottom of the page

topics:
- Cherry Picking
- Git Stash

Take reference from #17

**Comment by Bhavya-Chawla** [comment]
@charandeepsinghb , Can you please assign me this issue? I've started working on it already.

**Comment by Bhavya-Chawla** [comment]
Please have a look at these additions
![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/145850764/577cb15a-e32e-4ce4-8b6d-20afa2cfff7a)
![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/145850764/4fcbc2a4-7ff5-4e3d-a651-9e762830594c)
I've initiated PR #20 . Please have a look
