### ISSUE TITLE
Add logo of git in "Install Git" section

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#3]
A logo needs to be added at **1. Install Git \<logo here\>** heading

**Comment by wrth1337** [comment]
Hello @charandeepsinghb . I'd like to work on this issue.

**Comment by BuilderPrid** [comment]
Hey I would like to work on this. Can you assign this to me?

**Comment by BuilderPrid** [comment]
@charandeepsinghb i have added the git logo. Let me know if any other changes are desired.
Regards.

**Comment by charandeepsinghb** [comment]
@wrth1337, if you could add a PR with a logo of the same height as the header text, I'll assign it to you.

**Comment by wrth1337** [comment]
@charandeepsinghb Yes, I will create the pull request later. Thanks for assigning.

**Comment by charandeepsinghb** [comment]
The best code will be merged guys!
Appreciations 👍

**Comment by therefat** [comment]
assignee me

**Comment by charandeepsinghb** [comment]
Please fix the other issue if you are interested https://github.com/charandeepsinghb/learn-code-contribute/issues/5

**Comment by charandeepsinghb** [comment]
@therefat, If you fix this like I have suggested in the PR https://github.com/charandeepsinghb/learn-code-contribute/pull/4 comments I'll assign It to you. Add a PR.

The best PR will be merged!

Appreciations 👍

**Comment by Yashhuc** [comment]
I have added the git logo. Please review
