### ISSUE TITLE
Add GitHub icon logo

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#5]
Add GitHub icon next to the header

Icon (logo) placement: Find repositories \<icon here\>

Icon size: same as the header font

**Comment by BuilderPrid** [comment]
Assign me

**Comment by Bhavya-Chawla** [comment]
Your project looks interesting and innovative , I would really like to work on it.
Can you please assign me this issue?

**Comment by happyday123123** [comment]
this will be my first issue to start with, can I take this one?

**Comment by charandeepsinghb** [comment]
@Bhavya-Chawla you can work on https://github.com/charandeepsinghb/learn-code-contribute/issues/9

**Comment by charandeepsinghb** [comment]
@BuilderPrid add a PR I'll assign it to you

**Comment by charandeepsinghb** [comment]
@happyday123123 you can work on https://github.com/charandeepsinghb/learn-code-contribute/issues/10 add a PR

**Comment by Yashhuc** [comment]
I have tried to add the logo.Please review.
