### ISSUE TITLE
New Menu items

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#9]
Add new menu items:
Beginner
Advanced

**Comment by Bhavya-Chawla** [comment]
Can you elaborate a bit more about what I need to do here?

**Comment by charandeepsinghb** [comment]
Add two more items below these.
![IMG_20231028_053737](https://github.com/charandeepsinghb/learn-code-contribute/assets/110289710/bebe5e7a-1a12-454d-adc2-fbce2879f0dc)
Below Contributions

**Comment by Bhavya-Chawla** [comment]
Do I also have to add the content in those pages?

**Comment by Bhavya-Chawla** [comment]
Does this work @charandeepsinghb ?
![Screenshot 2023-10-28 112127](https://github.com/charandeepsinghb/learn-code-contribute/assets/145850764/1ffee76b-3645-446b-910a-787c2c6d1eb9)
![Screenshot 2023-10-28 112143](https://github.com/charandeepsinghb/learn-code-contribute/assets/145850764/ec4e9b85-30ec-47b2-89d7-b67a7b3aa54a)
![Screenshot 2023-10-28 112154](https://github.com/charandeepsinghb/learn-code-contribute/assets/145850764/470f0c78-1149-4b7f-908a-9cdffbeabae6)

**Comment by charandeepsinghb** [comment]
Good @Bhavya-Chawla but keep the commit messages consistent and proper
